----TOTAL_EMPLOYEES
SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM HR_ANALYTICS;

DESC HR_ANALYTICS;

---Total Employees by Gender
SELECT GENDER,
       COUNT(*) AS TOTAL_EMPLOYEES
FROM HR_ANALYTICS
GROUP BY GENDER;

---Average Age of Employees
SELECT ROUND(AVG(AGE),2) AS AVERAGE_AGE
FROM HR_ANALYTICS;

---Average Monthly Income
SELECT ROUND(AVG(MONTHLYINCOME),2) AS AVERAGE_MONTHLY_INCOME
FROM HR_ANALYTICS;

---Attrition Rate
SELECT
ROUND(
(SUM(CASE WHEN ATTRITION='Yes' THEN 1 ELSE 0 END)
/COUNT(*))*100,2) AS ATTRITION_RATE
FROM HR_ANALYTICS;

-- Attrition Count
SELECT ATTRITION, COUNT(*)
FROM HR_ANALYTICS
GROUP BY ATTRITION;

-- Attrition by Department
SELECT DEPARTMENT,
       COUNT(*)
FROM HR_ANALYTICS
WHERE ATTRITION='Yes'
GROUP BY DEPARTMENT;

-- Attrition by Job Role
SELECT JOBROLE,
       COUNT(*)
FROM HR_ANALYTICS
WHERE ATTRITION='Yes'
GROUP BY JOBROLE;

--Attrition by Gender
SELECT GENDER,
       ATTRITION,
       COUNT(*) AS TOTAL
FROM HR_ANALYTICS
GROUP BY GENDER,ATTRITION
ORDER BY GENDER;

---Overtime vs Attrition
SELECT OVERTIME,
       ATTRITION,
       COUNT(*) AS TOTAL
FROM HR_ANALYTICS
GROUP BY OVERTIME,ATTRITION;


---Avg Income by Department
SELECT DEPARTMENT,
       ROUND(AVG(MONTHLYINCOME),2) AS AVG_INCOME
FROM HR_ANALYTICS
GROUP BY DEPARTMENT
ORDER BY AVG_INCOME DESC;

---Avg Income by Job Role
SELECT JOBROLE,
       ROUND(AVG(MONTHLYINCOME),2) AS AVG_INCOME
FROM HR_ANALYTICS
GROUP BY JOBROLE
ORDER BY AVG_INCOME DESC;

--Avg Years at Company
SELECT ROUND(AVG(YEARSATCOMPANY),2) AS AVG_YEARS
FROM HR_ANALYTICS;

---Attrition by Education Field
SELECT EDUCATIONFIELD,
       COUNT(*) AS EMPLOYEES_LEFT
FROM HR_ANALYTICS
WHERE ATTRITION='Yes'
GROUP BY EDUCATIONFIELD
ORDER BY EMPLOYEES_LEFT DESC;

---Attrition by Marital Status
SELECT MARITALSTATUS,
       COUNT(*) AS EMPLOYEES_LEFT
FROM HR_ANALYTICS
WHERE ATTRITION='Yes'
GROUP BY MARITALSTATUS;


---Employees with Highest Income
SELECT EMPLOYEENUMBER,
       JOBROLE,
       MONTHLYINCOME
FROM HR_ANALYTICS
ORDER BY MONTHLYINCOME DESC
FETCH FIRST 10 ROWS ONLY;

---Top 10 Employees with Maximum Years at Company
SELECT EMPLOYEENUMBER,
       YEARSATCOMPANY
FROM HR_ANALYTICS
ORDER BY YEARSATCOMPANY DESC
FETCH FIRST 10 ROWS ONLY;


---Job Satisfaction Distribution
SELECT JOBSATISFACTION,
       COUNT(*) AS EMPLOYEES
FROM HR_ANALYTICS
GROUP BY JOBSATISFACTION
ORDER BY JOBSATISFACTION;


---Work-Life Balance Distribution
SELECT WORKLIFEBALANCE,
       COUNT(*) AS EMPLOYEES
FROM HR_ANALYTICS
GROUP BY WORKLIFEBALANCE
ORDER BY WORKLIFEBALANCE;

---Employees by Business Travel
SELECT BUSINESSTRAVEL,
       COUNT(*) AS TOTAL_EMPLOYEES
FROM HR_ANALYTICS
GROUP BY BUSINESSTRAVEL;


---High-Risk Employees
SELECT EMPLOYEENUMBER,
       JOBROLE,
       DEPARTMENT,
       JOBSATISFACTION,
       WORKLIFEBALANCE
FROM HR_ANALYTICS
WHERE OVERTIME='Yes'
AND JOBSATISFACTION<=2
AND WORKLIFEBALANCE<=2;


---Attrition Percentage by Department
SELECT
DEPARTMENT,
ROUND(
SUM(CASE WHEN ATTRITION='Yes' THEN 1 ELSE 0 END)
*100.0/COUNT(*),2) AS ATTRITION_PERCENTAGE
FROM HR_ANALYTICS
GROUP BY DEPARTMENT
ORDER BY ATTRITION_PERCENTAGE DESC;


---Average Monthly Income by Education
SELECT EDUCATION,
ROUND(AVG(MONTHLYINCOME),2) AS AVG_INCOME
FROM HR_ANALYTICS
GROUP BY EDUCATION
ORDER BY AVG_INCOME DESC;
